language: objective-c

osx_image: xcode7.2
xcode_project: WatsonDeveloperCloud.xcodeproj
xcode_scheme: WatsonDeveloperCloud
xcode_sdk: iphonesimulator9.2

#xcode_scheme: WatsonCore
before_install:
- brew update
- brew install carthage


before_script:
    - carthage update --platform iOS
# after_success:
# - bash <(curl -s https://codecov.io/bash)

#script:
# - xcodebuild clean build  -scheme WatsonDeveloperCloud -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

#- xcodebuild clean build  -scheme WatsonDeveloperCloud -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1'
